title: NSF SBIR
theme: uswds-jekyll

baseurl: ""
permalink: pretty
deadline: June 14th, 2017

styles:
  - /assets/css/styles.css
sass:
  style: compressed

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true
  - src: /assets/js/main.js
    async: true

collections:
  apply:
    permalink: /how-to-apply/:path/
    output: true
  events:
    output: false
  timeline:
    output: false

defaults:
  - scope:
      path: "_apply"
    values:
      layout: secondary-narrow

awards_api:
  date_start: '06/01/2016'
  date_end: '12/31/2016'
  active_start_date: '11/30/2016'
  update_to_current_time: false
  reset: false
  printFields:
    - id
    - awardeeCity
    - awardeeName
    - awardeeStateCode
    - date
    - expDate
    - fundsObligatedAmt
    - fundProgramName
    - poName
    - title
    - awardee
