title: NSF SBIR
theme: uswds-jekyll

baseurl: ""
permalink: pretty
deadline: June 14th, 2017

styles:
  - /assets/css/styles.css
sass:
  style: compressed

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

collections:
  apply:
    permalink: /how-to-apply/:path/
    output: true
  events:
    output: false
  timeline:
    output: false

defaults:
  - scope:
      path: "_apply"
    values:
      layout: docs
