title: NSF SBIR
theme: uswds-jekyll

url: https://seedfund.nsf.gov
baseurl: ""
permalink: pretty
deadline: June 14, 2017

app_process: active
# app_process: inactive

styles:
  - /assets/css/styles.css
sass:
  style: compressed

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

collections:
  apply:
    permalink: /how-to-apply/:path/
    output: true
  events:
    output: false
  timeline:
    output: false
  styleguide:
    output: true
    permalink: /styleguide/:path/

defaults:
  - scope:
      path: "_apply"
    values:
      layout: secondary-narrow
  - scope:
      path: "_styleguide"
    values:
      layout: styleguide
      include_subnav: true

awards_api:
  active_date_is_now: true
  active_date: '06/13/2017'
  fundProgramName: phase
  reset: false
  recent_date: '06/01/2016'
  printFields:
    - id
    - awardeeName
    - date
    - expDate
    - fundsObligatedAmt
    - fundProgramName
    - poName
    - title
    - abstractText
    - startDate
    - endDate
    - awardeeCity
    - awardeeCountryCode
    - awardeeStateCode
    - awardeeZipCode
    - awardeeAddress
    - piFirstName
    - piMiddeInitial
    - piLastName
    - piPhone
    - piEmail

portfolio_api:
  # Figure out dates
  date_start: '06/01/2013'
  date_end: '06/01/2016'
  active_start_date: '11/30/2016'
  update_to_current_time: false
  reset: false
  printFields:
    - id
    - awardeeName
    - date
    - expDate
    - fundsObligatedAmt
    - fundProgramName
    - poName
    - title
    - abstractText
    - startDate
    - endDate
    - awardeeCity
    - awardeeCountryCode
    - awardeeStateCode
    - awardeeZipCode
    - awardeeAddress
    - piFirstName
    - piMiddeInitial
    - piLastName
    - piPhone
    - piEmail

topics_api:
  # Figure out dates
  date_start: '06/01/2013'
  date_end: '06/01/2017'
  active_start_date: '11/30/2016'
  update_to_current_time: true
  fundProgramName: phase
  reset: false
  printFields:
    - id
    - awardeeName
    - date
    - expDate
    - fundsObligatedAmt
    - fundProgramName
    - poName
    - title
    - abstractText
    - startDate
    - endDate
    - awardeeCity
    - awardeeCountryCode
    - awardeeStateCode
    - awardeeZipCode
    - awardeeAddress
    - piFirstName
    - piMiddeInitial
    - piLastName
    - piPhone
    - piEmail

exclude:
- _data/portfolio.yml
- data/portfolio.yml
