title: NSF SBIR
theme: uswds-jekyll

baseurl: ""
permalink: pretty
deadline: June 14th, 2017

styles:
  - /assets/css/uswds-overrides.css

scripts:
  - src: /assets/uswds/js/uswds.min.js
    async: true

collections:
  apply:
    permalink: /how-to-apply/:path/
    output: true

defaults:
  - scope:
      path: "_apply"
    values:
      layout: docs
